### ISSUE TITLE
Costum filter

### ISSUE THREAD

**Issue by gorankrajnc** [tochoromero/vuejs-smart-table#6]
Hi
How we can make costum filter to 3 or more columen.
I like filtering from Name, surname and Age?

Thanks
Goran

**Comment by tochoromero** [comment]
Hello @gorankrajnc, you can do custom filters with as many columns as you want, it is documented here:
https://tochoromero.github.io/vuejs-smart-table/filtering/#custom-filters

Note how the custom filter function receives the `filterValue` and the `row`. The `row` is your actual object with all its properties, you can use the `filterValue` and apply it to as many properties in your `row` as you want. You just need to return `true` if the row should be displayed or `false` otherwise.

**Comment by npnpnpnpnpnp** [comment]
Hi @tochoromero, first of all, thanks for this amazing plugin! Love it so far. But also have a question regarding filtering multiple columns. You pointed at the custom filter functions but I can't seem to get it right. 

I have 3 columns with, say, title and authors (which is an array of all listed authors). For the authors, I created a custom filter like this: 

```
    authorFilter(filterValue, row) {
      let filter = null
      row.fields.author.map(author => {
        filter = author.fields.title.includes(filterValue)
      })
      return filter
    }
```

Now, in the filter configuration object, do I have to specify one filter with something like this: 

```
 filters: {
        title: { value: '', keys: ['fields.title'], custom: this.authorFilter }
      }
```

or go for multiple filters like this: 

```
      filters: {
        title: { value: '', keys: ['fields.title' ] },
        author: { value: '', custom: this.authorFilter },
      },
```


If it's the last case, how would you tell your `v-model` to consider values from all filters, not only one with let's say `v-model="filter. title.value"`?

Any help is greatly appreciated. Thank you in advance!
